build:
	gcc ex1.c -o ex1 -lpthread -Wall
	gcc ex2.c -o ex2 -lpthread -Wall
	gcc multiply_seq.c -o multiply_seq -lpthread -Wall
	gcc ex3.c -o ex3 -lpthread -Wall
	gcc ex4.c -o ex4 -lpthread -Wall
	gcc ex5.c -o ex5 -lpthread -Wall
	gcc strassen.c -o strassen -lpthread -Wall
	
clean:
	rm -rf ex1 ex2 multiply_seq ex3 ex4 ex5 strassen